/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;
import login.MenuLogin;

/**
 *
 * @author Nanang M32
 */
public class MenuUtamaDS extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtamaDS() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pn_main = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btdashbord = new javax.swing.JLabel();
        pn_alternatif = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btalternatif = new javax.swing.JLabel();
        pn_kriteria = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btkriteria = new javax.swing.JLabel();
        pn_perhitungan = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btperhitungan = new javax.swing.JLabel();
        proses = new javax.swing.JLabel();
        pn_laporan = new javax.swing.JPanel();
        pn_line6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btlaporan = new javax.swing.JLabel();
        pn_keluar = new javax.swing.JPanel();
        pn_line11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btkeluar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_nilai = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btpenilaian = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1566, 768));

        pn_kiri.setBackground(new java.awt.Color(5, 77, 76));
        pn_kiri.setForeground(new java.awt.Color(255, 255, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 768));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Aplikasi SPK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoo.png"))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SIstem Pemilihan Siswa Berprestasi");

        pn_main.setBackground(new java.awt.Color(5, 77, 76));

        pn_line.setBackground(new java.awt.Color(5, 77, 76));
        pn_line.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home_2.png"))); // NOI18N

        btdashbord.setBackground(new java.awt.Color(255, 255, 0));
        btdashbord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btdashbord.setForeground(new java.awt.Color(255, 255, 255));
        btdashbord.setText("Dashboard");
        btdashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdashbordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btdashbordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btdashbordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addComponent(btdashbord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btdashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_alternatif.setBackground(new java.awt.Color(5, 77, 76));

        pn_line1.setBackground(new java.awt.Color(5, 77, 76));
        pn_line1.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userrr.png"))); // NOI18N

        btalternatif.setBackground(new java.awt.Color(255, 255, 0));
        btalternatif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btalternatif.setForeground(new java.awt.Color(255, 255, 255));
        btalternatif.setText("Data Alternatif");
        btalternatif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btalternatifMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btalternatifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btalternatifMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_alternatifLayout = new javax.swing.GroupLayout(pn_alternatif);
        pn_alternatif.setLayout(pn_alternatifLayout);
        pn_alternatifLayout.setHorizontalGroup(
            pn_alternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_alternatifLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addComponent(btalternatif)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_alternatifLayout.setVerticalGroup(
            pn_alternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_alternatifLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pn_alternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btalternatif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kriteria.setBackground(new java.awt.Color(5, 77, 76));

        pn_line2.setBackground(new java.awt.Color(5, 77, 76));
        pn_line2.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Power Bi 2021_2.png"))); // NOI18N

        btkriteria.setBackground(new java.awt.Color(255, 255, 0));
        btkriteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btkriteria.setForeground(new java.awt.Color(255, 255, 255));
        btkriteria.setText("Bobot Kriteria");
        btkriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btkriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btkriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btkriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_kriteriaLayout = new javax.swing.GroupLayout(pn_kriteria);
        pn_kriteria.setLayout(pn_kriteriaLayout);
        pn_kriteriaLayout.setHorizontalGroup(
            pn_kriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kriteriaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addComponent(btkriteria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_kriteriaLayout.setVerticalGroup(
            pn_kriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_perhitungan.setBackground(new java.awt.Color(5, 77, 76));

        pn_line3.setBackground(new java.awt.Color(5, 77, 76));
        pn_line3.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/News.png"))); // NOI18N

        btperhitungan.setBackground(new java.awt.Color(255, 255, 0));
        btperhitungan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btperhitungan.setForeground(new java.awt.Color(255, 255, 255));
        btperhitungan.setText("Matriks Perhitungan");
        btperhitungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btperhitunganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btperhitunganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btperhitunganMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_perhitunganLayout = new javax.swing.GroupLayout(pn_perhitungan);
        pn_perhitungan.setLayout(pn_perhitunganLayout);
        pn_perhitunganLayout.setHorizontalGroup(
            pn_perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perhitunganLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(19, 19, 19)
                .addComponent(btperhitungan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_perhitunganLayout.setVerticalGroup(
            pn_perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perhitunganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_perhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btperhitungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        proses.setBackground(new java.awt.Color(255, 255, 255));
        proses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        proses.setForeground(new java.awt.Color(255, 255, 0));
        proses.setText("LAPORAN");

        pn_laporan.setBackground(new java.awt.Color(5, 77, 76));

        pn_line6.setBackground(new java.awt.Color(5, 77, 76));
        pn_line6.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line6Layout = new javax.swing.GroupLayout(pn_line6);
        pn_line6.setLayout(pn_line6Layout);
        pn_line6Layout.setHorizontalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line6Layout.setVerticalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N

        btlaporan.setBackground(new java.awt.Color(255, 255, 0));
        btlaporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btlaporan.setForeground(new java.awt.Color(255, 255, 255));
        btlaporan.setText("Laporan");
        btlaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btlaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btlaporanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_laporanLayout = new javax.swing.GroupLayout(pn_laporan);
        pn_laporan.setLayout(pn_laporanLayout);
        pn_laporanLayout.setHorizontalGroup(
            pn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_laporanLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(19, 19, 19)
                .addComponent(btlaporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_laporanLayout.setVerticalGroup(
            pn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_keluar.setBackground(new java.awt.Color(5, 77, 76));

        pn_line11.setBackground(new java.awt.Color(5, 77, 76));
        pn_line11.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line11Layout = new javax.swing.GroupLayout(pn_line11);
        pn_line11.setLayout(pn_line11Layout);
        pn_line11Layout.setHorizontalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line11Layout.setVerticalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keluar.png"))); // NOI18N

        btkeluar.setBackground(new java.awt.Color(255, 255, 255));
        btkeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btkeluar.setForeground(new java.awt.Color(255, 153, 0));
        btkeluar.setText("KELUAR");
        btkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btkeluarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_keluarLayout = new javax.swing.GroupLayout(pn_keluar);
        pn_keluar.setLayout(pn_keluarLayout);
        pn_keluarLayout.setHorizontalGroup(
            pn_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_keluarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_keluarLayout.setVerticalGroup(
            pn_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_keluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_keluarLayout.createSequentialGroup()
                .addGroup(pn_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_line11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("MASTER DATA");

        pn_nilai.setBackground(new java.awt.Color(5, 77, 76));

        pn_line4.setBackground(new java.awt.Color(5, 77, 76));
        pn_line4.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Document_1.png"))); // NOI18N

        btpenilaian.setBackground(new java.awt.Color(255, 255, 0));
        btpenilaian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btpenilaian.setForeground(new java.awt.Color(255, 255, 255));
        btpenilaian.setText("Data Nilai Alternatif");
        btpenilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btpenilaianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btpenilaianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btpenilaianMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_nilaiLayout = new javax.swing.GroupLayout(pn_nilai);
        pn_nilai.setLayout(pn_nilaiLayout);
        pn_nilaiLayout.setHorizontalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nilaiLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(19, 19, 19)
                .addComponent(btpenilaian)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_nilaiLayout.setVerticalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btpenilaian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_alternatif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_perhitungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_nilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(proses))
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(28, 28, 28)
                .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(pn_alternatif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_perhitungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(proses)
                .addGap(18, 18, 18)
                .addComponent(pn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(24, 115, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1266, 70));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancel_1.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1248, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pn_kanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(204, 204, 204));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Welcome.png"))); // NOI18N
        pn_utama.add(jLabel12, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btdashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashbordMouseEntered
        pn_main.setBackground(new Color(24,115,100));
        pn_line.setBackground(new Color(5,77,76));
        
    }//GEN-LAST:event_btdashbordMouseEntered

    private void btdashbordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashbordMouseExited
     pn_main.setBackground(new Color(5,77,76));
     pn_line.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btdashbordMouseExited

    private void btdashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashbordMouseClicked
      pn_main.setBackground(new Color(24,115,100));
      pn_line.setBackground(new Color(5,77,76));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuDashbord());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btdashbordMouseClicked

    private void btalternatifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btalternatifMouseClicked
      pn_alternatif.setBackground(new Color(24,115,100));
      pn_line1.setBackground(new Color(5,77,76));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuAlternatif());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btalternatifMouseClicked

    private void btalternatifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btalternatifMouseEntered
        pn_alternatif.setBackground(new Color(24,115,100));
        pn_line1.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btalternatifMouseEntered

    private void btalternatifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btalternatifMouseExited
        pn_alternatif.setBackground(new Color(5,77,76));
        pn_line1.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btalternatifMouseExited

    private void btkriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkriteriaMouseClicked
      pn_kriteria.setBackground(new Color(24,115,100));
      pn_line2.setBackground(new Color(5,77,76));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuKriteria());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btkriteriaMouseClicked

    private void btkriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkriteriaMouseEntered
      pn_kriteria.setBackground(new Color(24,115,100));
      pn_line2.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btkriteriaMouseEntered

    private void btkriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkriteriaMouseExited
        pn_kriteria.setBackground(new Color(5,77,76));
        pn_line2.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btkriteriaMouseExited

    private void btperhitunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btperhitunganMouseClicked
      pn_perhitungan.setBackground(new Color(24,115,100));
      pn_line3.setBackground(new Color(5,77,76));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuPerhitungan());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btperhitunganMouseClicked

    private void btperhitunganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btperhitunganMouseEntered
        pn_perhitungan.setBackground(new Color(24,115,100));
        pn_line3.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btperhitunganMouseEntered

    private void btperhitunganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btperhitunganMouseExited
        pn_perhitungan.setBackground(new Color(5,77,76));
        pn_line3.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btperhitunganMouseExited

    private void btlaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlaporanMouseClicked
      pn_laporan.setBackground(new Color(24,115,100));
      pn_line6.setBackground(new Color(5,77,76));  
      
      pn_utama.removeAll();
      pn_utama.add(new Laporan());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btlaporanMouseClicked

    private void btlaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlaporanMouseEntered
        pn_laporan.setBackground(new Color(24,115,100));
        pn_line6.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btlaporanMouseEntered

    private void btlaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlaporanMouseExited
        pn_laporan.setBackground(new Color(5,77,76));
        pn_line6.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btlaporanMouseExited

    private void btkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkeluarMouseClicked
      
     int a=JOptionPane.showConfirmDialog(this, "Apakah yakin anda ingin Keluar ?",
             "Konfirmasi",JOptionPane.YES_NO_OPTION);
     if(a==0){
      dispose();
      new MenuLogin().setVisible(true);
     }
    }//GEN-LAST:event_btkeluarMouseClicked

    private void btkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkeluarMouseEntered
        pn_keluar.setBackground(new Color(235,235,235));
        pn_line11.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btkeluarMouseEntered

    private void btkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkeluarMouseExited
       pn_keluar.setBackground(new Color(5,77,76));
       pn_line11.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btkeluarMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btpenilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpenilaianMouseClicked
      pn_nilai.setBackground(new Color(24,115,100));
      pn_line4.setBackground(new Color(5,77,76));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuPenilaian_Kriteria());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btpenilaianMouseClicked

    private void btpenilaianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpenilaianMouseEntered
        pn_nilai.setBackground(new Color(24,115,100));
        pn_line4.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btpenilaianMouseEntered

    private void btpenilaianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpenilaianMouseExited
        pn_nilai.setBackground(new Color(5,77,76));
        pn_line4.setBackground(new Color(5,77,76));
    }//GEN-LAST:event_btpenilaianMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaDS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btalternatif;
    private javax.swing.JLabel btdashbord;
    private javax.swing.JLabel btkeluar;
    private javax.swing.JLabel btkriteria;
    private javax.swing.JLabel btlaporan;
    private javax.swing.JLabel btpenilaian;
    private javax.swing.JLabel btperhitungan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pn_alternatif;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_keluar;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_kriteria;
    private javax.swing.JPanel pn_laporan;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line11;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_line6;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_nilai;
    private javax.swing.JPanel pn_perhitungan;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JLabel proses;
    // End of variables declaration//GEN-END:variables

    private void MenuDashbord() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
